# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

target 'Foodly' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  pod 'AFNetworking', '~> 3.0'
  pod 'SDWebImage', '~> 4.0'
  pod "youtube-ios-player-helper", "~> 0.1.4"
  pod 'Realm'

  target 'FoodlyTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'FoodlyUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
